### ISSUE TITLE
Why does the bot give a warning for an invalid link?

### ISSUE THREAD

**Issue by MrLivixx** [MegaVasiliy007/nika#3]
![image](https://user-images.githubusercontent.com/54632865/94581446-c9877080-0283-11eb-9010-a5c514c2fd9a.png)
link 
![image](https://user-images.githubusercontent.com/54632865/94581475-d015e800-0283-11eb-8282-32c5d470209b.png)

**Comment by M1chnt** [comment]
Это печально

**Comment by Walkyst** [comment]
Ну думаю логично всё, потому что код так написан, если есть в discord.js сделать проверку на валидность инвайта, то сделайте PR

**Comment by MrLivixx** [comment]
> Ну думаю логично всё, потому что код так написан, если есть возможность в discord.js сделать проверку на валидность инвайта, то ждём PR

Она есть... но работает ли? 
https://github.com/MegaVasiliy007/nika/blob/654aa6202570f70ca7909fa028e3a49a14b4002c/nika.js#L59

**Comment by MegaVasiliy007** [comment]
Каждая проверка через fetchInvite делает запрос к дискорду. Если делать запрос на каждый чих, бот уйдет в лимиты.

**Comment by M1chnt** [comment]
Может вы мне снимите варн?

**Comment by M1chnt** [comment]
> Каждая проверка через fetchInvite делает запрос к дискорду. Если делать запрос на каждый чих, бот уйдет в лимиты.

Может вы мне снимите варн?

**Comment by Walkyst** [comment]
> > Каждая проверка через fetchInvite делает запрос к дискорду. Если делать запрос на каждый чих, бот уйдет в лимиты.
> 
> Может вы мне снимите варн?

https://sdc.su/form
